module.exports.descriptors=[
    "urban",
    "historic",
    "modern",
    "coastal",
    "suburban",
    "industrial",
    "rural",
    "scenic",
    "vibrant",
    "cultural",
    "industrial",
    "traditional",
    "dynamic",
    "eco-friendly",
    "metropolitan",
    "quaint",
    "residential",
    "bustling",
    "artistic",
    "technological",
    "elegant",
    "sustainable",
    "artistic",
    "sporty",
    "commercial",
    "picturesque",
    "peaceful",
    "commercial",
    "mountainous",
    "historic",
    "cosmopolitan",
    "family-friendly",
    "sophisticated",
    "rustic",
    "charming",
    "innovative",
    "growing",
    "dynamic",
    "affluent",
    "cozy",
    "energetic",
    "adventurous",
    "green",
    "contemporary",
    "lively",
    "traditional",
    "welcoming",
    "historic",
    "genteel",
    "vintage",
    "trendy",
    "artisanal",
    "authentic",
    "progressive",
    "resilient",
    "expansive",
    "compact",
    "well-preserved"
]



module.exports.places =[
    "city",
    "town",
    "village",
    "suburb",
    "rural area",
    "countryside",
    "district",
    "neighborhood",
    "municipality",
    "resort",
    "downtown",
    "outskirts",
    "cabin",
    "farm",
    "forest",
    "beach",
    "lake",
    "mountain",
    "valley",
    "coast",
    "island",
    "peninsula",
    "desert",
    "swamp",
    "riverbank",
    "plateau",
    "hill",
    "wilderness",
    "urban area",
    "subdivision",
    "gated community",
    "historic site",
    "skyscraper",
    "high-rise",
    "loft",
    "apartment",
    "condominium",
    "mansion",
    "cottage",
    "retreat",
    "community",
    "campground",
    "marina",
    "shopping center",
    "industrial park",
    "warehouse",
    "plaza",
    "courtyard",
    "pavilion",
    "marketplace",
    "garden",
    "park",
    "residential area",
    "business district",
    "academic campus",
    "retirement community",
    "studio"
]
